"use client";

import React from "react";
import { Sparkles } from "lucide-react";
import { Tooltip } from "antd";

export interface HmsAiGeneratedBadgeProps {
  label?: string;
  tooltipText?: string;
}

export const HmsAiGeneratedBadge: React.FC<HmsAiGeneratedBadgeProps> = ({
  label = "AI Suggestion",
  tooltipText = "Generated by Clinical AI. Physician review & explicit approval required.",
}) => {
  return (
    <Tooltip title={tooltipText}>
      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-purple-100 text-purple-700 border border-purple-200 cursor-help select-none">
        <Sparkles className="w-3.5 h-3.5 text-purple-600 animate-pulse" />
        <span>{label}</span>
      </span>
    </Tooltip>
  );
};
